osx bugfixes

diff --git a/git-open-pull b/git-open-pull
--- a/git-open-pull
+++ b/git-open-pull
@@ -53,24 +53,24 @@
 #       [github]
 #               user = ....
 #               password = ....
-#       [git-open-pull]
-#               base-account = ....
+#       [gitOpenPull]
+#               baseAccount = ....
 #               base = master
 
-PYTHON_CMD=`/usr/bin/env python`
+PYTHON_CMD=`/usr/bin/which python`
 [ $? != 0 ] && echo "unable to find 'python' command" && exit 1;
-GIT_CMD=`/usr/bin/env git`
+GIT_CMD=`/usr/bin/which git`
 [ $? != 0 ] && echo "unable to find 'git' command" && exit 1;
 
 # grab defaults where we can
 #####################
-BASE_ACCOUNT=`$GIT_CMD config --get git-open-pull.base-account`
-BASE_REPO=`$GIT_CMD config --get git-open-pull.base-repo`
-BASE_BRANCH=`$GIT_CMD config --get git-open-pull.base || echo "master"`
+BASE_ACCOUNT=`$GIT_CMD config --get gitOpenPull.baseAccount`
+BASE_REPO=`$GIT_CMD config --get gitOpenPull.baseRepo`
+BASE_BRANCH=`$GIT_CMD config --get gitOpenPull.base || echo "master"`
 GITHUB_USER=`$GIT_CMD config --get github.user`
 GITHUB_PASSWORD=`$GIT_CMD config --get github.password`
 FEATURE_BRANCH=`$GIT_CMD describe --contains --all HEAD`
-ISSUE_NUMBER=`echo $FEATURE_BRANCH | sed -r -e 's/.*_([0-9]+)$/\1/'`
+ISSUE_NUMBER=`echo $FEATURE_BRANCH | perl -p -e 's/.*_([0-9]+)$/\1/'`
 if [ "$ISSUE_NUMBER" == "$FEATURE_BRANCH" ]; then 
     ISSUE_NUMBER=""; 
 fi
@@ -113,6 +113,7 @@ if [ -z "$GITHUB_USER" ]; then
     read -p "github username: " GITHUB_USER
 fi
 if [ -z "$GITHUB_PASSWORD" ]; then
+    echo "using github username: $GITHUB_USER"
     # turn off echo to the shell
     stty -echo 
     read -p "github password: " GITHUB_PASSWORD; echo
@@ -120,13 +121,13 @@ if [ -z "$GITHUB_PASSWORD" ]; then
 fi
 
 if [ -z "$BASE_ACCOUNT" ]; then
-    read -p "remote github account to pull changes into: " BASE_ACCOUNT
-    $GIT_CMD config git-open-pull.base_account $BASE_ACCOUNT
+    read -p "remote github account to merge changes into: " BASE_ACCOUNT
+    $GIT_CMD config gitOpenPull.baseAccount $BASE_ACCOUNT
 fi
 
 if [ -z "$BASE_REPO" ]; then
     read -p "github repsitory on $BASE_ACCOUNT to pull changes into: " BASE_REPO
-    $GIT_CMD config git-open-pull.base_repo $BASE_REPO
+    $GIT_CMD config gitOpenPull.baseRepo $BASE_REPO
 fi
 
 if [ -z "$ISSUE_NUMBER" ]; then
@@ -164,13 +165,13 @@ try:
 except ImportError:
     import json
 import sys
-data = json.loads(sys.stdin.read())
+data = json.loads(sys.stdin.read().replace("\n",""))
 if "message" in data:
     print "ERROR verifying issue number: ", data["message"]
 else:
     print data.get("state", "unknown-issue")
 ')
-
+[[ $? != 0 ]] && echo "unknown error $ISSUE_JSON" && exit 1
 [[ "$ISSUE_STATE" =~ "ERROR" ]] && echo $ISSUE_STATE && exit 1
 
 if [ "$ISSUE_STATE" != "open" ]; then
@@ -184,9 +185,10 @@ try:
 except ImportError:
     import json
 import sys
-data = json.loads(sys.stdin.read())
+data = json.loads(sys.stdin.read().replace("\n",""))
 print data["title"]
 ')
+[[ $? != 0 ]] && echo "unknown error extracting issue title $ISSUE_JSON" && exit 1
 
 
 # check for source branch
@@ -201,7 +203,7 @@ try:
 except ImportError:
     import json
 import sys
-data = json.loads(sys.stdin.read())
+data = json.loads(sys.stdin.read().replace("\n",""))
 data = [x for x in data if x.get("name") == sys.argv[-1]]
 print len(data)
 ' "$branch_name")
@@ -215,7 +217,7 @@ try:
 except ImportError:
     import json
 import sys
-data = json.loads(sys.stdin.read())
+data = json.loads(sys.stdin.read().replace("\n",""))
 data = [x.get("name") for x in data]
 print ", ".join(data)
 '
@@ -224,14 +226,14 @@ fi
 
 echo "Opening pull request on $BASE_ACCOUNT/$BASE_REPO"
 echo "Issue: $ISSUE_NUMBER ($ISSUE_TITLE)"
-echo "pulling from $FEATURE_BRANCH into $BASE_ACCOUNT/$BASE"
+echo "pulling from $FEATURE_BRANCH into $BASE_ACCOUNT/$BASE_REPO branch $BASE_BRANCH"
 read -p "confirm [y/n]:" confirm
 if [ "$confirm" != "y" ]; then
     echo "exiting";
     exit 1;
 fi
 
-json="{\"issue\":$ISSUE_NUMBER, \"base\":\"$BASE\", \"head\":\"$FEATURE_BRANCH\"}"
+json="{\"issue\":$ISSUE_NUMBER, \"base\":\"$BASE_BRANCH\", \"head\":\"$FEATURE_BRANCH\"}"
 endpoint="https://api.github.com/repos/$BASE_ACCOUNT/$BASE_REPO/pulls"
 PULL_JSON=`curl --silent -H "Accept: application/vnd.github-pull.text+json,application/json" -u "$GITHUB_USER:$GITHUB_PASSWORD" --data-binary "$json" $endpoint`
 PULL_STATUS=$(echo $PULL_JSON | $PYTHON_CMD -c '
@@ -240,7 +242,7 @@ try:
 except ImportError:
     import json
 import sys
-data = json.loads(sys.stdin.read())
+data = json.loads(sys.stdin.read().replace("\n",""))
 pull_link = data.get("html_url")
 if not pull_link:
     print "ERROR updating issue to a pull request: ", data.get("message")
