move all python code into the bash helper function
much tidy, fewer quoting, wow

diff --git a/git-open-pull b/git-open-pull
--- a/git-open-pull
+++ b/git-open-pull
@@ -71,31 +71,56 @@ if [ -z "$GIT_CMD" ] || ! $GIT_CMD --version >/dev/null 2>&1 ; then
     exit 1
 fi
 
-python_data_script() {
-    local SCRIPT=$1
-    local OPT_ARG=$2
-    
-    $PYTHON_CMD -c "
+python_helper() {
+    $PYTHON_CMD -c '
+import sys
 try:
     import json
 except ImportError:
     import simplejson as json
-import sys
-data = sys.stdin.read().strip().replace('\n',r'\n').replace('\r','')
-data = json.loads(data)
-$SCRIPT
-" $OPT_ARG
-}
 
-json_escape() {
-    echo "$1" | $PYTHON_CMD -c "
-import sys
-try:
-    import json
-except ImportError:
-    import simplejson as json
-sys.stdout.write(json.dumps(sys.stdin.read().rstrip()))
-"
+if sys.argv[1] == "json_escape":
+    # take either a second argument, or stdin
+    input_txt = None
+    if len(sys.argv) > 2:
+        input_txt = sys.argv[2]
+    else:
+        input_txt = sys.stdin.read().strip()
+    sys.stdout.write(json.dumps(input_txt))
+    sys.exit(0)
+
+# all following commands take a json blob as the second argument
+data = json.loads(sys.argv[2].replace("\r","").replace("\n",""))
+
+if sys.argv[1] == "get_field":
+    field = sys.argv[3]
+    if field in data:
+        print(data[field])
+        sys.exit(0)
+    sys.exit(1)
+
+if sys.argv[1] == "count_branches":
+    matches = [x for x in data if x.get("name") == sys.argv[3]]
+    print(len(matches))
+    sys.exit(0)
+
+if sys.argv[1] == "print_branches":
+    names = [x.get("name") for x in data]
+    print(", ".join(names))
+    sys.exit(0)
+
+if sys.argv[1] == "check_pull_request":
+    pull_link = data.get("html_url")
+    if not pull_link:
+        print("ERROR updating issue to a pull request: " + data.get("message"))
+        for error in data.get("errors", []):
+            if error.get("message"):
+                print("  --> ERROR DETAIL: " + error.get("message"))
+    else:
+        print("Pull Request Opened")
+        print(pull_link)
+
+' "$@"
 }
 
 # grab defaults where we can
@@ -216,10 +241,7 @@ if [ -z "$GITHUB_TOKEN" ]; then
     echo "... getting access token (run with --save to save access token)"
     endpoint="https://api.github.com/authorizations"
     OAUTH_JSON=`curl --silent -H "$otp_header" -u "$GITHUB_USER:$GITHUB_PASSWORD" -d "{\"scopes\":[\"repo\"],\"note\":\"git-open-pull $BASE_ACCOUNT/$BASE_REPO\"}" $endpoint`
-    GITHUB_TOKEN=$(echo $OAUTH_JSON | python_data_script '
-if "token" in data:
-    print(data["token"])
-')
+    GITHUB_TOKEN=$(python_helper get_field "$OAUTH_JSON" token)
 
     if [ -z "$GITHUB_TOKEN" ]; then
         echo $OAUTH_JSON
@@ -248,20 +270,15 @@ if [ -z "$ISSUE_NUMBER" ]; then
     if [ "$ISSUE_NUMBER" == "c" ]; then
         read -p "issue title: " ISSUE_TITLE
         read -p "issue description: " ISSUE_DESCRIPTION
-        ISSUE_TITLE=$(json_escape "$ISSUE_TITLE")
-        ISSUE_DESCRIPTION=$(json_escape "$ISSUE_DESCRIPTION")
+        ISSUE_TITLE=$(python_helper json_escape "$ISSUE_TITLE")
+        ISSUE_DESCRIPTION=$(python_helper json_escape "$ISSUE_DESCRIPTION")
         endpoint="https://api.github.com/repos/$BASE_ACCOUNT/$BASE_REPO/issues"
         json="{\"title\": $ISSUE_TITLE, \"body\": $ISSUE_DESCRIPTION}"
         ISSUE_JSON=`curl --silent -H "Accept: application/vnd.github-issue.text+json,application/json" --data-binary "$json" "$endpoint?access_token=$GITHUB_TOKEN"`
-        ISSUE_NUMBER=$(echo $ISSUE_JSON | python_data_script '
-if "number" not in data:
-    print("ERROR verifying issue number: %r" % data)
-else:
-    print(data.get("number"))
-')
-        if ! echo $ISSUE_NUMBER | egrep -q '^[0-9]+$'; then
-            echo "Error creating issue $ISSUE_NUMBER"
-            exit 1;
+        ISSUE_NUMBER=$(python_helper get_field "$ISSUE_JSON" number)
+        if [ $? != 0 ] || [ -z "ISSUE_NUMBER" ] ; then
+            echo "Error creating issue: $ISSUE_JSON"
+            exit 1
         fi
 
         echo "created issue $ISSUE_NUMBER"
@@ -309,23 +326,22 @@ fi
 # endpoint => /repos/:user/:repo/issues/:id
 endpoint="https://api.github.com/repos/$BASE_ACCOUNT/$BASE_REPO/issues/$ISSUE_NUMBER"
 ISSUE_JSON=`curl --silent -H "Accept: application/vnd.github-issue.text+json,application/json" "$endpoint?access_token=$GITHUB_TOKEN"`
-ISSUE_STATE=$(echo $ISSUE_JSON | python_data_script '
-if "message" in data:
-    print("ERROR verifying issue number: %r" % data["message"])
-else:
-    print(data.get("state", "unknown-issue"))
-')
-[[ $? != 0 ]] && echo "unknown error $ISSUE_JSON" && exit 1
-[[ "$ISSUE_STATE" =~ "ERROR" ]] && echo $ISSUE_STATE && exit 1
+ISSUE_STATE=$(python_helper get_field "$ISSUE_JSON" state)
+if [ $? != 0 ] || [ -z "$ISSUE_STATE" ]; then
+    echo "Error verifying issue number: $ISSUE_JSON"
+    exit 1
+fi
 
 if [ "$ISSUE_STATE" != "open" ]; then
     echo ""
     echo "Error: $BASE_ACCOUNT/$BASE_REPO issue $ISSUE_NUMBER is $ISSUE_STATE"
     exit 1;
 fi
-ISSUE_TITLE=$(echo $ISSUE_JSON | python_data_script 'print(data["title"])')
-[[ $? != 0 ]] && echo "unknown error extracting issue title $ISSUE_JSON" && exit 1
-
+ISSUE_TITLE=$(python_helper get_field "$ISSUE_JSON" title)
+if [ $? != 0 ] || [ -z "$ISSUE_TITLE" ]; then
+    echo "Error extracting issue title from $ISSUE_JSON"
+    exit 1
+fi
 
 # check for source branch
 # endpoint -> /repos/:user/:repo/branches
@@ -333,19 +349,13 @@ source_user=$(echo "$FEATURE_BRANCH" | awk -F ':' '{print $1}')
 endpoint="https://api.github.com/repos/$source_user/$BASE_REPO/branches"
 branch_name=$(echo "$FEATURE_BRANCH" | awk -F ':' '{print $NF}')
 BRANCHES_JSON=`curl --silent -H "Accept: application/vnd.github-branches.text+json,application/json" "$endpoint?access_token=$GITHUB_TOKEN"`
-BRANCH_EXISTS=$(echo $BRANCHES_JSON | python_data_script '
-data = [x for x in data if x.get("name") == sys.argv[-1]]
-print(len(data))
-' "$branch_name")
+BRANCH_EXISTS=$(python_helper count_branches "$BRANCHES_JSON" "$branch_name")
 if [ "$BRANCH_EXISTS" != "1" ]; then
     echo ""
     echo "Error: branch ($branch_name) does not exist in $source_user/$BASE_REPO"
     echo -n -e "\tvalid branches are: "
-    echo $BRANCHES_JSON | python_data_script '
-data = [x.get("name") for x in data]
-print(", ".join(data))
-'
-    exit 1;
+    python_helper print_branches "$BRANCHES_JSON"
+    exit 1
 fi
 
 echo "Opening pull request on $BASE_ACCOUNT/$BASE_REPO"
@@ -360,14 +370,4 @@ fi
 json="{\"issue\":$ISSUE_NUMBER, \"base\":\"$BASE_BRANCH\", \"head\":\"$FEATURE_BRANCH\"}"
 endpoint="https://api.github.com/repos/$BASE_ACCOUNT/$BASE_REPO/pulls"
 PULL_JSON=`curl --silent -H "Accept: application/vnd.github-pull.text+json,application/json" --data-binary "$json" "$endpoint?access_token=$GITHUB_TOKEN"`
-echo $PULL_JSON | python_data_script '
-pull_link = data.get("html_url")
-if not pull_link:
-    print("ERROR updating issue to a pull request: " + data.get("message"))
-    for error in data.get("errors", []):
-        if error.get("message"):
-            print("  --> ERROR DETAIL: " + error.get("message"))
-else:
-    print("Pull Request Opened")
-    print(pull_link)
-'
+python_helper check_pull_request "$PULL_JSON"
