allow PYTHON_CMD or GIT_CMD to be set from the environment
and use more elaborate command availability checks

diff --git a/git-open-pull b/git-open-pull
--- a/git-open-pull
+++ b/git-open-pull
@@ -61,10 +61,16 @@
 #               baseRepo = .....
 #               base = master
 
-PYTHON_CMD=`/usr/bin/which python`
-[ $? != 0 ] && echo "unable to find 'python' command" && exit 1;
-GIT_CMD=`/usr/bin/which git`
-[ $? != 0 ] && echo "unable to find 'git' command" && exit 1;
+PYTHON_CMD=${PYTHON_CMD:-$(which python)}
+if [ -z "$PYTHON_CMD" ] || ! $PYTHON_CMD --version >/dev/null 2>&1 ; then
+    echo "unable to find 'python' command"
+    exit 1
+fi
+GIT_CMD=${GIT_CMD:-$(which git)}
+if [ -z "$GIT_CMD" ] || ! $GIT_CMD --version >/dev/null 2>&1 ; then
+    echo "unable to find 'git' command"
+    exit 1
+fi
 
 # grab defaults where we can
 #####################
